# Generated by Django 5.2.7 on 2025-11-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
