# Generated by Django 5.2.7 on 2025-11-12 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='age',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='has_children',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='has_disability',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='household_size',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_employed',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='selected_form',
        ),
        migrations.CreateModel(
            name='CaseSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('urgency_score', models.IntegerField(default=5)),
                ('urgency_reasoning', models.TextField(blank=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('household_size', models.IntegerField(blank=True, null=True)),
                ('household_members', models.JSONField(blank=True, default=list)),
                ('has_children', models.BooleanField(blank=True, null=True)),
                ('monthly_income', models.FloatField(blank=True, null=True)),
                ('income_sources', models.JSONField(blank=True, default=list)),
                ('total_assets', models.FloatField(blank=True, null=True)),
                ('monthly_expenses', models.JSONField(blank=True, default=dict)),
                ('employment_status', models.CharField(blank=True, max_length=50)),
                ('current_employer', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('employment_duration', models.CharField(blank=True, max_length=100)),
                ('housing_situation', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('monthly_rent', models.FloatField(blank=True, null=True)),
                ('at_risk_of_homelessness', models.BooleanField(default=False)),
                ('has_disability', models.BooleanField(blank=True, null=True)),
                ('disability_details', models.TextField(blank=True)),
                ('has_medical_expenses', models.BooleanField(blank=True, null=True)),
                ('monthly_medical_costs', models.FloatField(blank=True, null=True)),
                ('has_health_insurance', models.BooleanField(blank=True, null=True)),
                ('citizenship_status', models.CharField(blank=True, max_length=100)),
                ('immigration_status', models.CharField(blank=True, max_length=100)),
                ('current_benefits', models.JSONField(blank=True, default=list)),
                ('has_emergency_needs', models.BooleanField(default=False)),
                ('emergency_details', models.TextField(blank=True)),
                ('structured_summary', models.JSONField(blank=True, default=dict)),
                ('ai_summary', models.TextField(blank=True)),
                ('recommended_programs', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_submission', to='chatbot.conversation')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['-urgency_score', '-submitted_at'], name='chatbot_cas_urgency_a0e6e0_idx'), models.Index(fields=['submitted_at'], name='chatbot_cas_submitt_ebf30f_idx')],
            },
        ),
    ]
